version: "3.8"

services:
  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/monitoring
      - prometheus-data:/monitoring
    command: --web.enable-lifecycle --config.file=/etc/monitoring/prometheus.yml  # If you use --web.enable-lifecycle you can reload configuration files (e.g. rules) without restarting Prometheus:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources # data source configuration
      - grafana-data:/var/lib/grafana # used to save dashboards

  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - "./monitoring:/config"
      - alertmanager-data:/data

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  bff_app:
    build:
      dockerfile: deployments/Bff.Dockerfile
    container_name: bff_app
    restart: unless-stopped
    volumes:
      - ./config:/bff/pkg/config
    ports:
      - "50050:50050"
    depends_on:
      - prometheus
      - mongo
      - grafana
      - alertmanager
      - node-exporter
      - elasticsearch
      - kibana

  product_app:
    build:
      dockerfile: deployments/Product.Dockerfile
    container_name: product_app
    restart: unless-stopped
    volumes:
      - ./config:/product/pkg/config
    ports:
      - "50053:50053"
    depends_on:
      - prometheus
      - mongo
      - grafana
      - alertmanager
      - node-exporter
      - elasticsearch
      - kibana

volumes:
  mongo-data:
  prometheus-data:
  grafana-data:
  alertmanager-data:
  elasticsearch-data: