server:
  appVersion: "1.0.0"
  host: "localhost"
  port: "50050"
  mode: "Dev"
  readTimeout: 5
  writeTimeout: 5
  maxHeaderBytes: 10
  ctxTimeout: 4

clients:
  productClientUrl: "localhost:50053"

logger:
  development: true
  encoding: "json"
  level: "info"

jaeger:
  host: "localhost:6832"
  serviceName: "Bff_Api"
  logSpans: false

metric:
  url: "localhost:7071"
  serviceName: "Bff_Api"