server:
  appVersion: "1.0.0"
  host: "0.0.0.0"
  port: "50050"
  mode: "Dev"
  readTimeout: 5
  writeTimeout: 5
  maxHeaderBytes: 10
  ctxTimeout: 4

clients:
  productClientUrl: "localhost:50051"

logger:
  development: true
  encoding: "json"
  level: "info"

jaeger:
  host: "localhost:6831"
  serviceName: "Bff_Api"
  logSpans: false

metric:
  url: "localhost:7070"
  serviceName: "Bff_Api"