server:
  appVersion: "1.0.0"
  host: "0.0.0.0"
  port: "50050"
  mode: "Dev"
  networkType: "tcp"
  ctxTimeout: 10

logger:
  development: true
  encoding: "json"
  level: "info"

jaeger:
  host: "localhost:6831"
  serviceName: "Bff_Api"
  logSpans: false

metric:
  url: "localhost:7070"
  serviceName: "Bff_Api"